FabricMC/fabric-loader

src/main/java/net/fabricmc/base/Fabric.java, src/main/java/net/fabricmc/base/launch/FabricClientTweaker.java, src/main/java/net/fabricmc/base/loader/Init.java, src/main/java/net/fabricmc/base/loader/Loader.java, src/main/java/net/fabricmc/base/loader/ModContainer.java, src/main/java/net/fabricmc/base/loader/ModInfo.java, src/main/java/net/fabricmc/base/loader/language/ILanguageAdapter.java, src/main/java/net/fabricmc/base/loader/language/JavaLanguageAdapter.java, src/main/java/net/fabricmc/base/util/VersionDeserializer.java, src/test/java/net/fabricmc/test/TestMod.java, src/test/java/net/fabricmc/test/mixin/MixinGuiMain.java, src/test/resources/fabricmc.test.mixins.client.json, src/test/resources/mod.json
**Do not merge, feedback wanted**
- Adds a language adapter interface allowing for mod developers to use other languages (Scala, Kotlin) that provide `object` singletons with main mod classes.
- Adds a ModContainer system that holds the mod info, the language adapter instance, and the mod instance.
- Adds a bare-bones test mod to demonstrate the system.
- Fixes deserializing `mod.json`s as previously there wasn't a `Version` deserializer.
=> [WIP] Mod loading

src/main/java/net/fabricmc/loader/language/JavaLanguageAdapter.java
I assumed canApplyInterface is called with `.` as a separator because of the replacement, but it actually does not.
This actually resolves the issue.
=> Actually fix bug causing ClientModInitializer/DedicatedServerModInitializers being loaded when they should not be

src/main/java/net/fabricmc/loader/FabricLoader.java
People are experiencing strange errors on first launch that are fixed on second launch. I believe this is caused by the short circuiting which prevents classpath mods from loading if the mods folder does not already exist.
=> Avoid short circuiting loading if mods folder does not already exist

Jenkinsfile, build.gradle, settings.gradle
also gets rid of the buildscript block, since its not needed anymore
as commented in the TODO: javadoc errors on some code, so i left it commented out
should probably be moved into a gradle snippet for reuse anyways
=> use maven-publish

src/main/java/net/fabricmc/loader/entrypoint/patches/EntrypointPatchHook.java
Check to see if the entry point is for Minecraft before attempting to apply a patch.
=> [dev/0.4] Do not apply Minecraft specific patch to non Minecraft games

src/main/java/net/fabricmc/loader/InstanceStorage.java
Fix #80 by using a the class's fully qualified name instead of a Class instance as the key to the map of initializers, since there can be multiple Class instances in an environment with multiple class loaders.
=> Fix only one a single mod initializer getting loaded

src/main/java/net/fabricmc/loader/entrypoint/minecraft/EntrypointPatchHook.java
In 1.14.4 fabric-loader was looking for the log output `LWJGL Version: {}` to find the correct method to inject into.
In 19w34a this was changed to `Backend library: {}`, this is a quick and easy fix to ensure mods get loaded at the correct time.
Ideally something less fragile would be used here, but for now this should be fine.
Fix tested in 1.14.4 and 19w34a
=> Fix injection point detection on 19w34a

build.gradle, gradle.properties, src/main/java/net/fabricmc/loader/FabricLoader.java, src/main/java/net/fabricmc/loader/discovery/BuiltinMetadataWrapper.java, src/main/java/net/fabricmc/loader/discovery/ModResolver.java, src/main/java/net/fabricmc/loader/game/GameProvider.java, src/main/java/net/fabricmc/loader/game/MinecraftGameProvider.java, src/main/java/net/fabricmc/loader/launch/FabricTweaker.java, src/main/java/net/fabricmc/loader/launch/common/FabricLauncherBase.java, src/main/java/net/fabricmc/loader/launch/knot/Knot.java, src/main/java/net/fabricmc/loader/metadata/BuiltinModMetadata.java, src/main/java/net/fabricmc/loader/minecraft/McVersionLookup.java, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
This allows declaring a dependency on a specific Minecraft version, including snapshots and pre-releases.
The MC version gets normalized to be (mostly) semver compliant, examples:
1.14
1.14.4
1.15-alpha.19.34.a (snapshot 19w34a)
1.14.4-rc.7 (pre-release 1.14.4-pre7)
=> Implement builtin mod feature, add builtin mod for Minecraft

gradle.properties, src/main/java/net/fabricmc/loader/api/SemanticVersion.java, src/main/java/net/fabricmc/loader/util/version/SemanticVersionImpl.java, src/main/java/net/fabricmc/loader/util/version/SemanticVersionPredicateParser.java, src/test/java/net/fabricmc/test/VersionParsingTests.java
This PR makes pre-release versions more available to dependency declarations and everything except lesser comparison should work more intuitively. The drawback is that an expression like "<1.2" will now permit a 1.2-prerelease until updated to "<1.2-" to set the bound just before any 1.2 pre-release version.
Versions with pre-release suffixes are no longer excluded, they are less
than their associated release and greater than the previous release.
Wildcard ranges automatically include pre-releases at the start and
exclude them at the end.
Carret (^, same major) and tilde (~, same major+minor) ranges exclude
pre-releases at the end, but not at the start without lowering it with
an empty pre-release (trailing -), e.g. "~1.15-".
The upper bound has to be specified with a pre-release now to …
=> Improve/fix semantic version parsing and comparison.

gradle.properties, src/main/java/net/fabricmc/loader/api/metadata/CustomValue.java, src/main/java/net/fabricmc/loader/api/metadata/ModMetadata.java, src/main/java/net/fabricmc/loader/discovery/BuiltinMetadataWrapper.java, src/main/java/net/fabricmc/loader/launch/knot/KnotClassLoader.java, src/main/java/net/fabricmc/loader/metadata/AbstractModMetadata.java, src/main/java/net/fabricmc/loader/metadata/BuiltinModMetadata.java, src/main/java/net/fabricmc/loader/metadata/CustomValueImpl.java, src/main/java/net/fabricmc/loader/metadata/LoaderModMetadata.java, src/main/java/net/fabricmc/loader/metadata/ModMetadataV0.java, src/main/java/net/fabricmc/loader/metadata/ModMetadataV1.java
This PR prepares GSON for removal or repackaging by offering a replacement custom value API and deprecating the old one. It also works around https://github.com/FabricMC/fabric-loader/issues/149 by forcing GSON class loading into InjectingURLClassLoader.
=> Replace GSON JsonElement in ModMetadata custom values, always delegate GSON to parent CL in KnotClassLoader.

src/main/java/net/fabricmc/loader/discovery/ModResolver.java
This makes 3 changes:
- When validating a mod ID against the regex this will print out a detailed list of the errors, rather than just `Mod '%s' does not match the requirements`. For example a mod id like: `buildCraftIA :)`it will print: `Mod id 'buildCraftIA :)' does not match the requirements because it contains invalid characters: ' ):ACI'!`. If there are multiple errors then they will appear like this:
```
Mod id `BuildCraftIA :)--------------------------------------------------------------` does not match the requirements because:
- It has more than 64 characters!
- It starts with an invalid character 'B' (it must be a lowercase a-z)
- It contains invalid characters: ' ):ACI'!
```
- When validating a required/recommended/breaks/conficting mod ID it will print the same information as …
=> Print a bit more information if the mod ID is invalid or a dependent mod has a version mismatch

gradle.properties, src/main/java/net/fabricmc/loader/entrypoint/EntrypointPatch.java, src/main/java/net/fabricmc/loader/entrypoint/minecraft/EntrypointPatchHook.java
Inject before the LDC node, does slightly shift the injection point on older versions.
Also added a moveBefore and moveAfter that work on instructions over opcodes.
Bump version.
=> Fix injection point in 19w38a

src/main/java/net/fabricmc/loader/EntrypointStorage.java, src/main/java/net/fabricmc/loader/discovery/ModResolver.java
- Adds the errors of "Could not look up entries for entrypoint Z!" as suppressed so they show up in crash reports (before they were just logged, so they only appeared in full logs)
- Changed some error messages:
- "Could not resolve valid mod collection (at: X requires Y@version)"
-> "Could not find required mod: X requires Y@version"
- "Could not resolve valid mod collection (at: X breaks Y@version)"
-> "Found conflicting mods: X breaks Y@version"
=> Improve error messages

src/main/java/net/fabricmc/loader/EntrypointStorage.java, src/main/java/net/fabricmc/loader/FabricLoader.java, src/main/java/net/fabricmc/loader/ModContainer.java, src/main/java/net/fabricmc/loader/api/entrypoint/PreLaunchEntrypoint.java, src/main/java/net/fabricmc/loader/api/entrypoint/PreMainEntrypoint.java, src/main/java/net/fabricmc/loader/entrypoint/minecraft/hooks/EntrypointClient.java, src/main/java/net/fabricmc/loader/entrypoint/minecraft/hooks/EntrypointServer.java, src/main/java/net/fabricmc/loader/entrypoint/minecraft/hooks/EntrypointUtils.java, src/main/java/net/fabricmc/loader/launch/FabricTweaker.java, src/main/java/net/fabricmc/loader/launch/knot/Knot.java, src/test/java/net/fabricmc/test/TestMod.java, src/test/resources/fabric.mod.json
The normal entrypoints execute fairly late and after MC did a lot of initialization work, which may be too late or less effective for some tasks.
This new preLaunch entrypoint happens when it is already safe to do anything from a class loading or fabric loader POV, but before any MC code executes. As mentioned in the PreLaunchEntrypoint some care has to be taken to not cause undesirable side effects like the static initializer of a MC class assuming some dependency being already initialized.
Language adapter, mod root path and entrypoint initialization had to be moved earlier, I am not aware of any reason why this has to be done late. Some elements were renamed to better reflect their actual purpose and the entry point invocation helper was expanded to remove some duplicated code.
=> Add preLaunch entrypoint executing just before the game launch

gradle.properties, src/main/java/net/fabricmc/loader/util/mappings/MixinIntermediaryDevRemapper.java
This resolves an issue I had with running yarn 1.15-pre4 build 4 in-dev. MixinChunkRebuildTask.hookChunkBuild references `method_22785`, which became `render` in latest yarn. Mixin tries to remap this method with neither owner nor desc, presumably because it doesn't have a refmap or other context. MixinIntermediaryDevRemapper didn't support desc-less member remapping, which this PR fixes at least to the extent necessary to make Fabric API work in-dev with yarn .4.
The PR also tweaks some minor details. There are still some open issues around this class.
=> Fix MixinIntermediaryDevRemapper not maping member queries with null desc

build.gradle, gradle.properties, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
This is a supplementary PR for https://github.com/FabricMC/Mixin/pull/27.
Updates the mixins version to latest version.
Should fabric-loader's version be bumped with this PR as well (`0.7.2 -> 0.7.3`)?
Also consider:
> Looking at the ASM change for the supported versions, it looks like it now auto detects the correct version, so that shouldnt be an issue. It will still need testing on j8 thought to 14, but that can be done when running with loader.
> 
> _Originally posted by @modmuss50 in https://github.com/FabricMC/Mixin/pull/27#issuecomment-566970798_
=> Update mixin version to 0.8+build17

build.gradle, gradle.properties, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
ASM 7.3 seems to have added support for Java 14's records, as far I can can see tiny remapper may need to handle these. As records are still a preview feature I dont think it is a high priority issue. I have included some links bellow with more info
- [Merge branch 'asm8-record' into 'master'](https://gitlab.ow2.org/asm/asm/commit/db802e6eb64784567b81277f28734421b9dc878e)
- [JEP 359: Records (Preview)](https://openjdk.java.net/jeps/359)
Updating ASM should be fairly safe, I have tested on j8 and j15 with fabric api. Mixin no longer has a set list of supported ASM version so that does not need to be updated.
I have also bumped the loom version, as loader was using a very old version, at somepoint we can evaluate the use of loom for loader see (#161).
=> Update asm to 7.3.1 for java 15 support

src/main/java/net/fabricmc/api/Environment.java, src/main/java/net/fabricmc/api/EnvironmentInterface.java, src/main/java/net/fabricmc/api/EnvironmentInterfaces.java
This makes them show up in javadocs, and it's useful to know when a class or a method is environment-only.
=> Add Documented to Environment* annotations

src/main/java/net/fabricmc/loader/EntrypointStorage.java
An up-to-date version of #153's fix for uninformative crashlogs if a throwable that doesn't subclass Exception is thrown during entrypoint loading.
=> catch Throwables instead of just Exceptions during entrypoint loading

src/main/java/net/fabricmc/loader/discovery/ModCandidateSet.java, src/main/java/net/fabricmc/loader/discovery/ModResolver.java, src/main/java/net/fabricmc/loader/entrypoint/EntrypointTransformer.java, src/main/java/net/fabricmc/loader/entrypoint/minecraft/EntrypointPatchBranding.java, src/main/java/net/fabricmc/loader/game/GameProviders.java, src/main/java/net/fabricmc/loader/game/MinecraftGameProvider.java, src/main/java/net/fabricmc/loader/launch/knot/MixinServiceKnot.java, src/main/java/net/fabricmc/loader/metadata/ModMetadataV0.java
Minimally invasive removal of Guava uses, part of the dependency stripping efforts to avoid conflicts with the game and load order sensitivity.
=> Remove uses of Guava

src/main/java/net/fabricmc/loader/EntrypointStorage.java, src/main/java/net/fabricmc/loader/FabricLoader.java, src/main/java/net/fabricmc/loader/api/EntrypointException.java, src/main/java/net/fabricmc/loader/api/FabricLoader.java, src/main/java/net/fabricmc/loader/api/entrypoint/EntrypointContainer.java, src/main/java/net/fabricmc/loader/entrypoint/EntrypointContainerImpl.java, src/main/java/net/fabricmc/loader/entrypoint/minecraft/hooks/EntrypointUtils.java
This is for #199 
This adds a getEntrypointProvider(Object) method which optionally returns the mod container the entrypoint is from (assuming the object is actually an entrypoint).
Also included is some more rich exception handling where the mod which causes an entrypoint error is mentioned, (some restructuring may be needed).
=> Add methods to get the ModContainer which as provided an entrypoint

src/main/java/net/fabricmc/loader/entrypoint/minecraft/hooks/EntrypointUtils.java
Fixes https://github.com/FabricMC/fabric-loader/pull/207/files#r395191539
As that PR brings logs like: 
```
[13:22:51] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughresources'!
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
at net.minecraft.class_3176.<init>(class_3176.java:100) ~[intermediary-server.jar:?]
at …
```
=> Do not ignore exception

src/main/java/net/fabricmc/loader/entrypoint/applet/AppletFrame.java
Tested with b1.7.3 MultiMC instance from [js6pak/fabric-loader](https://github.com/js6pak/fabric-loader/releases) with this build of fabric-loader [fabric-loader-0.7.8%2Blocal.jar](https://ss.modmuss50.me/fabric-loader-0.7.8%2Blocal.jar)
Thanks to @Mumfrey for noticing this. Thanks Ashleez for finding and reporting the bug.
=> Make AppletForcedShutdownListener run a daemon thread, fixes the game locking up on close.

src/main/java/net/fabricmc/loader/api/FabricLoader.java
Due to 20w22a+ dedicated server game instance changes (#269), the game instance may not always be available.
=> Clarify nullability of getGameInstance method

src/main/java/net/fabricmc/loader/discovery/ModResolver.java, src/main/java/net/fabricmc/loader/metadata/ModMetadataParser.java
This prevents some more cryptic stack traces like this by actually blaming the mod that broke:
https://gist.github.com/modmuss50/7c13acaed89a56b491430cbb08fd34d4
Of course this is a tiny fix which may actually be the wrong way to approach it, so comment away.
=> Catch all exceptions json deserialization of mod metadata could throw.

src/main/java/net/fabricmc/loader/api/SemanticVersion.java, src/main/java/net/fabricmc/loader/api/VersionParsingException.java, src/main/java/net/fabricmc/loader/metadata/BuiltinModMetadata.java, src/main/java/net/fabricmc/loader/metadata/ModMetadataV1.java, src/main/java/net/fabricmc/loader/util/version/SemanticVersionImpl.java, src/main/java/net/fabricmc/loader/util/version/SemanticVersionPredicateParser.java, src/main/java/net/fabricmc/loader/util/version/StringVersionPredicateParser.java, src/main/java/net/fabricmc/loader/util/version/VersionDeserializer.java, src/main/java/net/fabricmc/loader/util/version/VersionParsingException.java, src/main/java/net/fabricmc/loader/util/version/VersionPredicateParser.java
Both `Version` and `SemanticVersion` have `parse` methods which throw `VersionParsingException` which is checked, forcing an internal loader import (which is discouraged). This moves the exception class into the API so it can be imported from there instead. Should be completely backwards compatible as anything catching the old one will catch the new subclass of it too.
=> Expose VersionParsingException in the API

src/main/java/net/fabricmc/loader/discovery/DirectoryModCandidateFinder.java
I noticed the fabric loader did not load mods if the "mods" directory was a symlink.
I have a "mods" directory on Dropbox so it is sync'd between PCs, and want to make a symlink to it under a game directory on each PC to get fabric to load mods in it.  On Windows, fabric is able to detect mods when "mods" is a directory junction, but on macOS and Linux, fabric does not load mods when "mods" is a symlink to a directory.
java.nio.file.Files.isDirectory() follows a symlink by default but Files.walk does not, so I guess this patch could fix it.
=> Allow the mods directory to be a symlink

src/main/java/net/fabricmc/loader/entrypoint/EntrypointTransformer.java, src/main/java/net/fabricmc/loader/launch/FabricTweaker.java, src/main/java/net/fabricmc/loader/launch/common/FabricLauncherBase.java
Fabric*Tweaker can now be used to launch fabric-loader on LaunchWrapper either as the primary tweaker, which should be functionally equivalent to launching with Knot (except for LaunchWrapper caveats ofc), or as a secondary tweaker, which allows fabric-loader (and mods, provided they were built for the right mappings) to run next to third-party tweaker-based mods.
See individual commits for details.
Fixes #202 
Fixes #168 
Partially #137 (only the LaunchWrapper part, I did not look at KnotCompatibilityClassLoader)
Tested configurations (both on MultiMC):
- All of Fabric 3 on LaunchWrapper (skipping Jumploader, no clue how to configure it)
- ReplayMod with a small subset of fabric-api (both compiled to `official` instead of `intermediary` mappings) running on Vivecraft (which includes …
=> Get LaunchWrapper / FabricTweaker working again

src/main/java/net/fabricmc/loader/FabricLoader.java, src/main/java/net/fabricmc/loader/api/FabricLoader.java, src/main/java/net/fabricmc/loader/game/GameProvider.java, src/main/java/net/fabricmc/loader/game/MinecraftGameProvider.java
The ``sanitize`` parameter removes the access token so it isn't accidentally exposed.
=> Add FabricLoader#getLaunchArguments(sanitize)

src/main/java/net/fabricmc/loader/metadata/V1ModMetadata.java
There was a change that was overlooked where if no mod provides an entrypoint, the list of entrypoints is null which causes an NPE.
This returns an empty list if no entrypoints of the key are found so old behavior is restored.
Fixes #323
=> Fix error from json migration

.github/workflows/release.yml, build.gradle
This does remove the build metadata: eg: `+build.123`
Before:
`modImplementation "net.fabricmc:fabric-loader:0.10.5+build.213"`
After:
`modImplementation "net.fabricmc:fabric-loader:0.10.5"`
=> Publish releases from github actions

src/main/java/net/fabricmc/loader/api/metadata/ModMetadata.java
(See https://fabricmc.net/wiki/documentation:fabric_mod_json_spec for more details).
*Edited for a proper description*
Loader currently treats these the same way as the wiki, and mods almost certainly do too. However the javadocs (and as far as I can tell *only* the javadocs) swap their meaning.
=> Fix the javadoc of getConflicts() and getBreaks() being the wrong way round

src/main/java/net/fabricmc/loader/api/SemanticVersion.java, src/main/java/net/fabricmc/loader/util/version/SemanticVersionImpl.java, src/test/java/net/fabricmc/test/VersionParsingTests.java
* Fix #286 
* Fix wrong test case
* Also fix catching incorrect exception in test case
Not sure if pre-release splitting should be moved to `SemanticVersionImpl` though.
> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows:
=> Fix #286 (SemVer pre-release comparison)

src/main/java/net/fabricmc/loader/discovery/DirectoryModCandidateFinder.java
Fixes #325
The gist of the issue is that some *nix operating systems like Mac OS name their metadata `.FILE_NAME.jar` which loader tries to load and fails.
=> Don't load .jar files which are *nix hidden files

src/main/java/net/fabricmc/loader/discovery/ClasspathModCandidateFinder.java
This PR fixes a small issue that makes it impossible to run fabric-loader in development.
In development, ClasspathModCandidateFinder adds the fabric-loader classes to KnotClassLoader as if it were a mod. This creates a situation where the entrypoint hooks are loaded on KnotClassLoader rather than AppClassLoader, which crashes the game when the hooks are run due to an unfrozen FabricLoader.
This fix involves a tiny heuristic that checks if `net/fabricmc/loader/FabricLoader.class` would be added to the classpath; if so, the dev classpath isn't added. This shouldn't affect any mods, unless they happen to also include a `net/fabricmc/loader/FabricLoader.class` file, which is probably not a good thing anyway.
=> Fix fabric-loader in developmental environments

src/main/java/net/fabricmc/loader/game/GameProvider.java, src/main/java/net/fabricmc/loader/game/MinecraftGameProvider.java, src/main/java/net/fabricmc/loader/launch/FabricTweaker.java, src/main/java/net/fabricmc/loader/launch/knot/Knot.java, src/main/java/net/fabricmc/loader/minecraft/McVersionLookup.java, src/main/java/net/fabricmc/loader/util/Arguments.java, src/main/java/net/fabricmc/loader/util/SystemProperties.java
Some MC builds, e.g. infdev, don't know about their version, so the only way to determine it is through external input. System properties aren't particularly launcher friendly, so this uses a normal program arg. The GameProvider interface has been tweaked such that it can leverage args to do its initial setup tasks.
=> Add support for specifying the game version via program argument.

src/main/java/net/fabricmc/api/EnvType.java
=> Fix typo in EnvType javadoc

src/main/java/net/fabricmc/loader/discovery/RuntimeModRemapper.java
The old behaviour of passing manifests through unmodified would break
signed jars, whose class signatures would be invalidated because of
remapping.
=> Fix manifests when doing runtime mod remapping

src/main/java/net/fabricmc/loader/metadata/ModMetadataParser.java
...which informs the user that they need to update fabric-loader.
This assumes that modders never create fabric.mod.json files with a schemaVersion newer than what a released version of fabric-loader supports, as then the error message wouldn't be very useful.
I'm primarily opening this so that users will be greeted with a better error message if they install a version of fabric-loader after this PR is merged, but before PRs like #334 is merged (at least, assuming you want to bump the schemaVersion to 2 for that PR - if you don't then this is just useful for when you do want to bump the version).
This results in a screen like this:
This doesn't affect the error message for versions less than 0 (which I assume is fine as we're unlikely to *decrease* the schema version in a normal build).
=> Add a more specific error message when finding positive (but unsupported) schema versions.

src/main/java/net/fabricmc/loader/FabricLoader.java, src/main/java/net/fabricmc/loader/api/metadata/ModMetadata.java, src/main/java/net/fabricmc/loader/discovery/BuiltinMetadataWrapper.java, src/main/java/net/fabricmc/loader/discovery/ModCandidateSet.java, src/main/java/net/fabricmc/loader/discovery/ModResolver.java, src/main/java/net/fabricmc/loader/metadata/BuiltinModMetadata.java, src/main/java/net/fabricmc/loader/metadata/V0ModMetadata.java, src/main/java/net/fabricmc/loader/metadata/V1ModMetadata.java, src/main/java/net/fabricmc/loader/metadata/V1ModMetadataParser.java, src/main/resources/fabric.mod.json
This PR does 1 thing:
- Adds aliases to dependency handling, so mods can depend on a mod's alias instead of its mod id.
Please review, there are some changes that I made that I wasn't sure of the standard of.
=> Add aliases to Fabric Loader

src/main/java/net/fabricmc/loader/FabricLoader.java, src/main/java/net/fabricmc/loader/metadata/DependencyOverrides.java, src/main/java/net/fabricmc/loader/metadata/V0ModMetadata.java, src/main/java/net/fabricmc/loader/metadata/V1ModMetadata.java
This PR is designed to give modpack developers more control over mod dependenies. It starts by looking for (but not creating) a `config/fabric_loader_dependencies.json` file with the following format:
```json
{
"version": 1,
"overrides": {
"oldermod": {
"depends": {}
},
"fragilemod": {
"breaks": {
"hackymod": "*"
}
}
}
}
```
If present this file will be used to replce the entire `depends` block of  `oldermod` with no dependencies, this is useful if a mod dpends on a specific version of minecraft, but works on another version without changes.
Secondly this can be used to add extra dependencies such as noting that `hackymod` breaks with `fragilemod`. This can be useful if a pack developer knows a specific mod that is added casuses common issues.
This can of course be used by any one, but …
=> Dependency Overrides

src/main/java/net/fabricmc/loader/FabricLoader.java, src/main/java/net/fabricmc/loader/ModContainer.java
This is a partial workaround for issue #152 where MC unconditionally
creates a file system for its Jar that conflicted with loader doing the
same earlier. A complete fix that also works if a mod happens to access
ModContainer.getRootPath for MC needs to prevent MC from creating the
already existing FileSystem and closing it.
Co-authored-by: shedaniel
This replaces https://github.com/FabricMC/fabric-loader/pull/291
=> Initialize mods' root path lazily.

build.gradle, gradle.properties, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
Not a lot of notable changes, the main concern with this update is the new mixin version number and the changes I made to mixin's build script. This leads the way to allow other changes to mixin down the line.
This still needs special testing on 0.5 loom.
=> Update mixin and asm to support newer java versions.

src/main/java/net/fabricmc/loader/FabricLoader.java
Changes the mod list printed in the log on launch to be on multiple lines to increase readability, instead of printing it on a single line.
Example:
```
[15:16:52] [main/INFO] (Fabric|Loader) [FabricLoader] Loading 47 mods:
- fabric@0.13.1+build.370-1.16
- fabric-api-base@0.1.3+12a8474c7c
- fabric-biomes-v1@0.2.7+059ea8667c
- fabric-blockrenderlayer-v1@1.1.4+c6a8ea897c
- fabric-command-api-v1@1.0.8+5ce533987c
- fabric-commands-v0@0.2.0+52d308367c
- fabric-containers-v0@0.1.8+045df74f7c
- fabric-content-registries-v0@0.1.9+059ea8667c
- fabric-crash-report-info-v1@0.1.2+b7f9825d7c
- fabric-dimensions-v1@1.0.0+a71b30537c
[rest of the list]
```
=> Display the mod list on multiple lines

src/main/java/net/fabricmc/loader/impl/entrypoint/EntrypointContainerImpl.java, src/main/java/net/fabricmc/loader/impl/entrypoint/EntrypointStorage.java
This disables lazy loading where it isn't possible due to the entry point potentially needing actual type based filtering.
=> Fix lazy loading (#313) breaking legacy entry points

src/main/legacyJava/net/fabricmc/loader/launch/server/FabricServerLauncher.java
I am unable to determine whether anyone relies on this entry point, so better to keep it working.
=> Re-add legacy FabricServerLauncher.main, just in case something depends on it

src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/discovery/ArgumentModCandidateFinder.java, src/main/java/net/fabricmc/loader/impl/discovery/DirectoryModCandidateFinder.java, src/main/java/net/fabricmc/loader/impl/discovery/ModDiscoverer.java, src/main/java/net/fabricmc/loader/impl/game/GameProvider.java, src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java, src/main/java/net/fabricmc/loader/impl/game/minecraft/launchwrapper/FabricTweaker.java, src/main/java/net/fabricmc/loader/impl/launch/FabricLauncherBase.java, src/main/java/net/fabricmc/loader/impl/util/Arguments.java, src/main/java/net/fabricmc/loader/impl/util/SystemProperties.java
This allows to specify extra mods with
- the --fabric.addMods program argument
- the -Dfabric.addMods jvm argument
Each takes a path separated list similar to the class path, e.g. `--fabric.addMods=path/modA.jar:/some/path/modB.jar` on Linux/MacOS or `--fabric.addMods=path/modA.jar;/some/path/modB.jar`on Windows
Valid entries for this list are:
- mod jars
- unpackaged mod directories (as used in-dev)
- \@-prefixed mod list files with one of the above in each line, similar to java/javac command line argument files
A mod list reference like `-Dfabric.addMods=@/some/modList.txt` expects modList.txt to contain e.g.
```
path/modA.jar
/some/path/modB.jar
```
This PR touches argument handling to ensure correct behavior with Launchwrapper and move some MC specific code where it belongs.
resolves …
=> Add --fabric.addMods / -Dfabric.addMods for adding extra path separator separated mods, list file if prefixed with @

.editorconfig, build.gradle, src/main/java/net/fabricmc/loader/impl/gui/FabricGuiEntry.java, src/main/java/net/fabricmc/loader/impl/gui/FabricMainWindow.java
Fixes most of : #489 
- Title bar respects system dark mode settings
- Menu bar title fixed
- Dock icon fixed (Java 9+ only)
- Fixed closing (I think there is a thread still around, hard to debug I can look into more if wanted)
Not fixed the dock title, not sure of a way to resolve that.
=> Improve error screen on MacOS

src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassDelegate.java
The map is being accessed concurrently, changing it to ConcurrentHashMap is sufficient since it's only used through the one `computeIfAbsent` invocation. I didn't find any other obvious thread safety issues.
Fixes #225
=> Fix thread-unsafe accesses to Knot's Metadata cache

src/main/java/net/fabricmc/loader/impl/discovery/ModCandidate.java, src/main/java/net/fabricmc/loader/impl/discovery/RuntimeModRemapper.java
Allow ModCandidate.copyToFile to replace existing files, needed becuase the RMR creates an empty temp file.
Fix RuntimeModRemapper error handling, outputPath can be null if it throws before the output path has been set, as seen with the above issue.
=> Fix RuntimeModRemapper

src/main/java/net/fabricmc/loader/impl/launch/server/FabricServerLauncher.java
This should make it more obvious what's actually wrong and using the absolute path highlights issues from operating in the wrong folder.
=> Clarify server launcher missing jar wording, use absolute path

src/main/java/net/fabricmc/loader/impl/util/mappings/MixinIntermediaryDevRemapper.java
This would otherwise throw a NPE inside the ArrayDeque implementation.
=> Fix MixinIntermediaryDevRemapper.mapMethodName crashing over unknown owner class

src/main/java/net/fabricmc/loader/minecraft/McVersionLookup.java
This has been broken since 0.11.4 but will only make a difference for pre-releases and release candidates
=> Fix MC version typo

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/launchwrapper/FabricTweaker.java, src/main/java/net/fabricmc/loader/impl/game/GameProvider.java, src/main/java/net/fabricmc/loader/impl/gui/FabricGuiEntry.java, src/main/java/net/fabricmc/loader/impl/gui/FabricMainWindow.java, src/main/java/net/fabricmc/loader/impl/gui/FabricStatusTree.java, src/main/java/net/fabricmc/loader/impl/launch/knot/Knot.java
Minecraft doesn't set up crash handling immediately; so for pre-launch entrypoints or Mixins to early loaded classes, exceptions will not produce crash reports. This can cause launchers (especially the vanilla one) to unhelpfully just report the game closing with an error code and nothing else. The crash will be in the logs, but this isn't always immediately obvious for a user to go check.
This PR recycles the dependency error/warning screen to show these early crashes visibly to the user so they at least have something to immediately report beyond just it closes upon start. The existing code only prints the messages for each `Throwable` so there's a copy stacktrace button to easily allow getting all the information there is.
=> Add a GUI for when the game crashes early

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McVersionLookup.java
Aims to build from what #517 (re-)broke. I made up versions to work within the constraints of what already exists (and sem ver): mainly the second combat snapshot inventing 1.14.5 (to be after 1.14.4 but the protocol/data versions suggest it is not a 1.15 snapshot), the fourth combat snapshot sitting between `1.15-rc.3` and `1.15-rc.4` (which both exist), and 20w14∞ sitting between `1.16-alpha.20.13.b` and `1.16-alpha.20.14.a`. Quite open to other ideas handling the edge cases in general.
| JSON ID | `version.info` | Normalized |
| --- | --- | --- |
| 1.14_combat-212796 | 1.14.3 - Combat Test | 1.14.3-rc.4.combat.1 |
| 1.14_combat-0 | Combat Test 2 | 1.14.5-combat.2 |
| 1.14_combat-3 | Combat Test 3 | 1.14.5-combat.3 |
| 1.15_combat-1 | Combat Test 4 | 1.15-rc.3.combat.4 |
| 1.15_combat-6 …
=> Try normalize special Minecraft versions

gradle.properties, src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/discovery/ModDiscoverer.java, src/main/java/net/fabricmc/loader/impl/discovery/ModResolver.java, src/main/java/net/fabricmc/loader/impl/discovery/ModSolver.java, src/main/java/net/fabricmc/loader/impl/discovery/ResultAnalyzer.java, src/main/java/net/fabricmc/loader/impl/metadata/ModDependencyImpl.java, src/main/resources/net/fabricmc/loader/Messages.properties
The first commit improves the information given to the user, the 2nd commit adds a workaround that emulates old Loader behavior for old schema versions.
=> Improve handling of env-disabled dependencies

src/main/java/net/fabricmc/loader/impl/discovery/ModCandidate.java, src/main/java/net/fabricmc/loader/impl/discovery/ModSolver.java, src/main/java/net/fabricmc/loader/impl/discovery/ResultAnalyzer.java, src/main/java/net/fabricmc/loader/impl/util/version/VersionIntervalImpl.java, src/main/java/net/fabricmc/loader/impl/util/version/VersionPredicateParser.java, src/main/resources/net/fabricmc/loader/Messages.properties
This change makes the solver also consider replacing mods that aren't invalid deps for other mods, but have unmet deps themselves.
Mod installation and replacement solutions now provide a proper upper bound and a better lower bound instead of just a somewhat bogus potential version.
Most removal solutions are now instructions to replacing a mod that is compatible with a set of requirements.
=> Improve resolution errors.

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/launchwrapper/FabricTweaker.java, src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/FormattedException.java, src/main/java/net/fabricmc/loader/impl/game/GameProvider.java, src/main/java/net/fabricmc/loader/impl/gui/FabricGuiEntry.java, src/main/java/net/fabricmc/loader/impl/launch/FabricLauncherBase.java, src/main/java/net/fabricmc/loader/impl/launch/knot/Knot.java
Previously early exceptions like from an invalid mixin config file reference wouldn't reach the log file, this PR fixes that. Error GUI invocation now happens through a special exception.
=> Handle uncaught exceptions by logging them and displaying the error gui, refactor error gui invocation

src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/discovery/BuiltinMetadataWrapper.java, src/main/java/net/fabricmc/loader/impl/discovery/ModDiscoverer.java, src/main/java/net/fabricmc/loader/impl/gui/FabricStatusTree.java, src/main/java/net/fabricmc/loader/impl/launch/FabricLauncherBase.java, src/main/java/net/fabricmc/loader/impl/metadata/BuiltinModMetadata.java, src/main/java/net/fabricmc/loader/impl/metadata/DependencyOverrides.java, src/main/java/net/fabricmc/loader/impl/metadata/LoaderModMetadata.java, src/main/java/net/fabricmc/loader/impl/metadata/V0ModMetadata.java, src/main/java/net/fabricmc/loader/impl/metadata/V1ModMetadata.java, src/main/java/net/fabricmc/loader/impl/metadata/VersionOverrides.java
This removes the static initializer / global singleton that incurs an useless exception as reported by https://github.com/FabricMC/fabric-loader/issues/563 and refactors everything to separate metadata parsing from override application.
I also added version overrides to the printout and moved both above mod resolution so they'll be in the log even if resolution fails.
The error gui now includes at least the exception class name (unless it is FormattedException) since just having the message is not always helpful.
=> Refactor dep/version overrides, tweak exception display

build.gradle, minecraft/minecraft-test/build.gradle, settings.gradle, src/main/java/net/fabricmc/loader/impl/util/Arguments.java, src/test/java/net/fabricmc/test/ArgumentParsingTests.java, src/test/java/net/fabricmc/test/V1ModJsonParsingTests.java
A recent update to the vanilla launcher started including empty argument values. Running the game (in dev) with `--clientId blah --xuid  --userType mojang --versionType release` (note the 2 spaces between --xuid and --usertype) is an easy way to reproduce the issue.
I dont believe the vanilla launcher should be supplying the empty --uid argument, but it does..
Mojang bug: https://bugs.mojang.com/browse/MCL-20810
* Fix dependency overrides not applying to nested mods.
* Fix unit tests not running.
* Update MC test project to 1.18
=> Fix main menu branding not working when using a Mojang login via the windows store launcher.

build.gradle, gradle.properties, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java, src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/game/GameProviderHelper.java, src/main/java/net/fabricmc/loader/impl/gui/FabricGuiEntry.java, src/main/java/net/fabricmc/loader/impl/launch/knot/Knot.java
This makes the Fabric Loader version available from the very start and uses it in a few important locations.
Draft because I am strongly considering to replace the mod json with a builtin declaration which should also save a little bit of class path scanning in production.
=> Source Fabric Loader version from a constant in FabricLoaderImpl, use in deobf game jar path

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/Log4jLogHandler.java, src/main/java/net/fabricmc/loader/impl/util/ManifestUtil.java
This should resolve CVE-2021-44228 for all versions.
It first checks if the Log4J version is affected and doesn't react to the system property, then removes the JNDI lookup. Reflection use avoids depending on Log4J core at compile time.
=> Strip Log4J2 substitution lookups as necessary

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/Log4jLogHandler.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java, src/main/java/net/fabricmc/loader/impl/game/GameProviderHelper.java
There were a few issues around extraneous class-to-file name conversions and very old Log4J versions didn't find its core component.
=> Fix unbundled external server jar handling

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/Log4jLogHandler.java
Removing the JNDI lookup on logger reconfiguration is just a precautionary measure, reconfiguration usually doesn't re-add it. The implementation however still complains about not finding the lookup again, this PR silences this useless complaint but keeps the reconfiguration removal trigger just in case.
=> Ignore missing Log4J JNDI lookup after reconfigures to avoid pointless spam

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McVersion.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McVersionLookup.java, minecraft/src/test/java/net/fabricmc/test/McVersionLookupTest.java, src/main/java/net/fabricmc/loader/impl/FormattedException.java, src/main/java/net/fabricmc/loader/impl/game/GameProviderHelper.java, src/main/java/net/fabricmc/loader/impl/launch/MappingConfiguration.java
This checks if the intermediary jar is correct for the MC version being used.
wip
=> Verify intermediary version

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java, src/main/java/net/fabricmc/loader/api/ModContainer.java, src/main/java/net/fabricmc/loader/api/metadata/ModOrigin.java, src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/ModContainerImpl.java, src/main/java/net/fabricmc/loader/impl/discovery/ArgumentModCandidateFinder.java, src/main/java/net/fabricmc/loader/impl/discovery/ClasspathModCandidateFinder.java, src/main/java/net/fabricmc/loader/impl/discovery/ModCandidate.java, src/main/java/net/fabricmc/loader/impl/discovery/ModCandidateFinder.java, src/main/java/net/fabricmc/loader/impl/discovery/ModDiscoverer.java, src/main/java/net/fabricmc/loader/impl/discovery/RuntimeModRemapper.java, src/main/java/net/fabricmc/loader/impl/game/GameProvider.java, src/main/java/net/fabricmc/loader/impl/metadata/ModOriginImpl.java, src/main/java/net/fabricmc/loader/impl/util/SystemProperties.java, src/main/legacyJava/net/fabricmc/loader/ModContainer.java
This adds a system property `fabric.classPathGroups` to specify class path groups. It takes paths separated by path separator, groups by double path separator. A group will cause all of its paths to be associated with a mod sourced from any of the paths.
The API addition `ModContainer.getRootPaths` exposes the multiple paths, existing methods have been deprecated or had their implementation adjusted. `getRootPath` and similar return only the first path and log a warning for the first access in production, always in-dev.
Most of the diff is from changing everything to handle multiple paths, which impacts everything from mod discovery to the resulting API exposure and class path impact.
With this feature it'll be possible to use more than one IDE project for a mod, e.g. to separate optional …
=> Add class path groups to map multiple class path entries to a mod

src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassLoader.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotCompatibilityClassLoader.java
should fix the inability to grab package annotations, reported by BasiqueEvangelist on Discord
=> Implement ClassLoader.findClass for java.lang.Package.getPackageInfo()

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McVersionLookup.java
```
1.19-Experimental.1 (raw=Deep Dark Experimental Snapshot 1 id=1.19_deep_dark_experimental_snapshot-1 name=Deep Dark Experimental Snapshot 1)
1.18-Experimental.7 (raw=1.18 experimental snapshot 7 id=1.18_experimental-snapshot-7 name=1.18 experimental snapshot 7)
```
Existing 1.18 exp snapshots will be unchanged.
=> Improve experimental version parsing.

src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/discovery/ModCandidate.java, src/main/java/net/fabricmc/loader/impl/discovery/ModDiscoverer.java, src/main/java/net/fabricmc/loader/impl/discovery/ResultAnalyzer.java, src/main/java/net/fabricmc/loader/impl/metadata/DependencyOverrides.java, src/main/java/net/fabricmc/loader/impl/metadata/MetadataVerifier.java, src/main/java/net/fabricmc/loader/impl/metadata/ModMetadataParser.java, src/main/java/net/fabricmc/loader/impl/metadata/ParseMetadataException.java, src/main/java/net/fabricmc/loader/impl/metadata/VersionOverrides.java, src/main/java/net/fabricmc/loader/impl/util/version/SemanticVersionImpl.java, src/test/java/net/fabricmc/test/V1ModJsonParsingTests.java
This PR intends to change two things:
a) Make the semver parser ignore anything after +, passing it through as-is
IMO there isn't any strong justification to limit the contents of the build metadata in our application, it is effectively only used for displaying purposes. Comparisons can always strip this metadata as it is being ignored anyway, so even spaces wouldn't be a serious issue for the space separated version predicates. This fixes fabric-api's use in e.g. `0.46.5+1.19_experimental` (can't normally have _ anywhere)
b) Warn early about non-semver versions that don't allow range comparisons and only in-dev
This required applying version overrides earlier to avoid useless warnings for setups using `$version`-like tokens with `-Dfabric.debug.replaceVersion`-based correction. The …
=> Allow arbitrary +build contents in semver parser, warn earlier about non-semver and only indev, refactoring

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/applet/AppletFrame.java
Versions before [1.6](https://launchermeta.mojang.com/v1/packages/20116297638f7c70cd046e25a6ac90fee4cae61a/1.6.json) like [1.5](https://launchermeta.mojang.com/v1/packages/924a2dcd8bdc31f8e9d36229811c298b3537bbc7/1.5.2.json) and [b1.7.3](https://launchermeta.mojang.com/v1/packages/44f6969326bd45aa00dcd3c4ca3a7c05ebb24c04/b1.7.3.json) lack `--username` and `--session`, instead they pass them directly
1.6
```json
"minecraftArguments": "--username ${auth_player_name} --session ${auth_session} --version ${version_name} --gameDir ${game_directory} --assetsDir ${game_assets}",
```
pre 1.6
```json
"minecraftArguments": "${auth_player_name} ${auth_session} --gameDir ${game_directory} --assetsDir ${game_assets}"
```
=> Add support for pre 1.6 arguments

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McVersionLookup.java
Strips the starting message from the version string
Examples of strings in old server versions
1.0.0 - `Starting minecraft server version 1.0.0`
b1.7.3 - `Starting minecraft server version Beta 1.7.3`
b1.0 - `Starting minecraft server version Beta 1.0`
a0.2.8 - `Starting minecraft server version 0.2.8`
a0.1.0 - `Starting minecraft server version 0.1.0`
Afaik there is no way to extract the version from classic server jars
Alpha server versions are independent from client versions and have a leading zero which the version regex doesn't support
=> Fix old server version parsing

gradle.properties, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/BundlerProcessor.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McLibrary.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McVersionLookup.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/launchwrapper/FabricTweaker.java, src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/discovery/ClasspathModCandidateFinder.java, src/main/java/net/fabricmc/loader/impl/game/GameProviderHelper.java, src/main/java/net/fabricmc/loader/impl/game/LibClassifier.java, src/main/java/net/fabricmc/loader/impl/game/LoaderLibrary.java, src/main/java/net/fabricmc/loader/impl/game/patch/GameTransformer.java, src/main/java/net/fabricmc/loader/impl/gui/FabricGuiEntry.java, src/main/java/net/fabricmc/loader/impl/launch/FabricLauncher.java, src/main/java/net/fabricmc/loader/impl/launch/FabricLauncherBase.java, src/main/java/net/fabricmc/loader/impl/launch/FabricMixinBootstrap.java, src/main/java/net/fabricmc/loader/impl/launch/knot/Knot.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassDelegate.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassLoader.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassLoaderInterface.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotCompatibilityClassLoader.java, src/main/java/net/fabricmc/loader/impl/launch/knot/MixinServiceKnot.java, src/main/java/net/fabricmc/loader/impl/util/SimpleClassPath.java, src/main/java/net/fabricmc/loader/impl/util/SystemProperties.java, src/main/java/net/fabricmc/loader/impl/util/UrlUtil.java, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
With this PR Loader should achieve proper isolation between the system/app class loader and the transforming class loader, hopefully eliminating remaining shadowing issues outside rather intentional misbehavior. All game and mod content is supposed to be on the transforming class loader, only Loader and its core libs should be loaded from the app CL.
A side effect of this effort is that the entire game including libraries becomes exposed to Mixin and other bytecode editing. This allows more direct patching of something like the Log4J issue in the future.
LibClassifier has been refactored to become usable by 3rd party game providers.
Mod class path handling still needs to be finalized.
=> Improve class loader isolation

src/main/java/net/fabricmc/loader/impl/discovery/ResultAnalyzer.java, src/main/resources/net/fabricmc/loader/Messages.properties
The solver may consider dependencies as unsatisfiable even if the referenced mod is there, but can't be loaded for other reasons. Those reasons can be anything involving a combination of secondary dependency failures, nesting load requirements (can't load a nested jar without its encompassing jar) or id conflicts. The PR handles these cases by giving a generic failure reason instead of no reason or a misleading reason as before.
=> Handle complex dependency failures more gracefully

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/Log4jLogHandler.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/Slf4jLogHandler.java, src/main/java/net/fabricmc/loader/impl/util/log/BuiltinLogHandler.java, src/main/java/net/fabricmc/loader/impl/util/log/ConsoleLogHandler.java, src/main/java/net/fabricmc/loader/impl/util/log/Log.java, src/main/java/net/fabricmc/loader/impl/util/log/LogHandler.java
This avoids printing early log output twice in benign scenarios. IMO it is the best approach to cover the gap between early logging needs and Log4J or any other game-provided logging lib being ready. The feature is opt-in from the game provider, the MC one enables it.
=> Delay log output until it can be displayed properly, except when errors occur

src/main/java/net/fabricmc/loader/impl/metadata/MetadataVerifier.java, src/main/java/net/fabricmc/loader/impl/util/version/SemanticVersionImpl.java, src/main/java/net/fabricmc/loader/impl/util/version/StringVersion.java
This should resolve some inconsistencies and make it easier to find related issues that aren't observable in-dev, but get introduced by the build.
=> Always fall back to lexicographical comparison when StringVersion is involved, always show non-semver warning

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/launchwrapper/FabricTweaker.java, src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/discovery/ClasspathModCandidateFinder.java, src/main/java/net/fabricmc/loader/impl/game/GameProviderHelper.java, src/main/java/net/fabricmc/loader/impl/game/LibClassifier.java, src/main/java/net/fabricmc/loader/impl/game/LoaderLibrary.java, src/main/java/net/fabricmc/loader/impl/launch/knot/Knot.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassDelegate.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassLoader.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassLoaderInterface.java, src/main/java/net/fabricmc/loader/impl/util/LoaderUtil.java, src/main/java/net/fabricmc/loader/impl/util/SystemProperties.java, src/main/java/net/fabricmc/loader/impl/util/UrlUtil.java, src/main/java/net/fabricmc/loader/impl/util/log/BuiltinLogHandler.java, src/main/java/net/fabricmc/loader/impl/util/log/Log.java, src/main/java/net/fabricmc/loader/impl/util/log/LogCategory.java
The server launchers were seen as game libraries, thus getting added to knot including the Loader libraries -> Loader existed on both class loaders.
This also adds some additional debugging tools.
=> Fix server launchers leaking their class path to knot CL, move to Path completely

src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassDelegate.java
These classes are not backed by a resource on the platform class loader,
but still load as expected.
=> Fix handling of classes defined at runtime.

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java, proguard.conf, src/main/java/net/fabricmc/loader/impl/launch/server/FabricServerLauncher.java
Resolves #665.
This PR makes Loader call the game's `main` method by using a MethodHandle instead of reflection. Doing this leaves no frames in the stack about the reflected invocation. It also changes the call to Knot in FabricServerLauncher to do the same.
Given proguard doesn't support polymorphism, this PR also adds a `dontwarn` directive to the proguard config to prevent it from complaining about it, as suggested in [this proguard issue](https://sourceforge.net/p/proguard/bugs/536/).
Tested using the installer's thing for using a custom loader JAR under 1.18.2 with no issues and with something weird that got `FabricServerLauncher#main` to run in debug that logged errors everywhere but launched a server. Are there instructions in how to properly debug loader?
=> Start the game using MethodHandles

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/launchwrapper/FabricTweaker.java, src/main/java/net/fabricmc/loader/impl/discovery/ClasspathModCandidateFinder.java, src/main/java/net/fabricmc/loader/impl/launch/knot/Knot.java
This avoids accidentally pulling in additional code sources, which isn't intended for the cp group feature.
=> Ignore class path group entries not on the class path

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/patch/EntrypointPatch.java
A simple forward method detector (same class only, easily expandable later) with some restrictions to avoid wasting time on older versions or the server side.
=> Add support for the MC client using a method that forwards to the actual main implementation as used by 22w24a

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java, src/main/java/net/fabricmc/loader/impl/game/LibClassifier.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassDelegate.java, src/main/java/net/fabricmc/loader/impl/util/SystemProperties.java
This is intended for applications like https://github.com/FabricMC/fabric-loader/issues/679 or other kinds of surrounding invocation mechanism.
=> Allow defining additional system libraries through a system property

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McLibrary.java
It should fix remapping issues in pre-1.13 which didn't ship realms classes directly in minecraft jar but as an external library.
Example of crash reports related to the remapping issue: https://paste.ee/p/Hy2wW
=> Fix realms library detection

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/patch/EntrypointPatch.java
22w32a added a non-synthetic method that interferes with the detection, this PR adds an explicit synthetic method check to suppress that.
=> Fix server entrypoint patch for 22w42a

src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassDelegate.java
This occurs when the first class to be loaded after mixin configs are added is referenced in an `IMixinConfigPlugin` belonging to one of said configs.
Sounds unlikely but it happens quite often with `MixinExtrasBootstrap` if mods reference it from both prelaunch and a mixin plugin.
=> Fix: Resolve duplicate class definition attempt.

build.gradle, gradle.properties, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
Ensure ASM is fetched from the fabric maven, this ensures that the ASM version has been mirrored for use by the launcher/installer.
No major rush to merge (Just here to go in alongside the next version), just nice to keep on top of. Supports Java 20 classes.
=> Update to ASM 9.4

src/main/java/net/fabricmc/loader/impl/util/mappings/MixinIntermediaryDevRemapper.java
Closes #745
Object has no super class, this fixes a crash when mixin tries to remap `Ljava/lang/Object;equals(Ljava/lang/Object;)Z`
Im not a massive fan of the use of checking the classname starts with `java/`, maybe one to revist when moving to mapping-io?
Test mod for future refrence [fabric-example-mod-1.0.0.zip](https://github.com/FabricMC/fabric-loader/files/10170664/fabric-example-mod-1.0.0.zip) (Rename to .jar)
=> Fix crash when trying to remap methods in Object.

src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassLoader.java
This fixes the `Configuration conflict: there is more than one oshi.architecture.properties file on the classpath` warning seen in the log file.
I am not 100% sure this fix is correct? Maybe it should de-dupe the resources from the 2 classloaders?
=> Don't combine resources from the two classloaders in KnotClassLoader.getResources

src/main/java/net/fabricmc/loader/impl/util/mappings/MixinIntermediaryDevRemapper.java
This PR fixes [this mixin from lithium](https://github.com/CaffeineMC/lithium-fabric/blob/f8e1b8dd95dd3239c7345b427d6da60a132a5f8d/src/main/java/me/jellysquid/mods/lithium/mixin/ai/task/launch/BrainMixin.java#L159) unable to be applied cleanly in 1.19.3 devlaunch using `1.19.3+build.2` yarn mappings.
=> Fixes MixinIntermediaryDevRemapper.mapMethodName unable to map ambiguous values

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/applet/AppletMain.java
This fixes sometimes occuring race conditions and changes the current behavior to what's suggested by the [AWT/Swing documentation](https://docs.oracle.com/javase/tutorial/uiswing/concurrency/initial.html)
=> Create and run applet on AWT EventQueue thread

src/main/java/net/fabricmc/loader/impl/metadata/V1ModMetadataParser.java, src/test/java/net/fabricmc/test/V1ModJsonParsingTests.java, src/test/resources/testing/parsing/v1/spec/any_icon_size.json, src/test/resources/testing/parsing/v1/spec/icon_sizes.json, src/test/resources/testing/parsing/v1/spec/no_icon.json
Fixes #741
This pull request also adds tests to verify that icons are parsed and chosen based on a preferred size correctly.
=> Fix icon objects in mod metadata not being parsed correctly

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/launchwrapper/FabricTweaker.java, src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/FormattedException.java, src/main/java/net/fabricmc/loader/impl/gui/FabricGuiEntry.java, src/main/java/net/fabricmc/loader/impl/launch/FabricLauncherBase.java, src/main/java/net/fabricmc/loader/impl/launch/knot/Knot.java, src/main/java/net/fabricmc/loader/impl/metadata/DependencyOverrides.java, src/main/java/net/fabricmc/loader/impl/util/Localization.java, src/main/resources/net/fabricmc/loader/Messages.properties, src/main/resources/net/fabricmc/loader/Messages_ja_JP.properties, src/test/java/net/fabricmc/test/LocalizationTests.java
=> Add more localization support

src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java
MultiMC and its forks apparently don't have Unicode support in their log window, so the mod list dump appears broken:
<details>
<summary>Broken table formatting</summary>
</details>
This PR makes the table use ASCII characters instead, so it displays correctly on all systems.
<details>
<summary>New ASCII-only formatting</summary>
```
[14:15:11] [INFO] [FabricLoader/]: Loading 78 mods:
- bettersleeping 0.6.0+1.19
|-- bettersleeping-core 0.6.0
\-- org_apache_commons_commons-text 1.9
- cloth-config 9.0.93
\-- cloth-basic-math 0.6.1
- fabric-api 0.68.1+1.19.3
|-- fabric-api-base 0.4.19+8d1895cf72
|-- fabric-api-lookup-api-v1 1.6.18+49abcf7e72
|-- fabric-biome-api-v1 12.0.0+689f5e7172
|-- fabric-block-api-v1 1.0.3+12bfe4ea72
|-- fabric-blockrenderlayer-v1 1.1.28+c6af733c72
|-- …
```
=> Switch to ASCII characters for mod list tree formatting

build.gradle, junit/build.gradle
This allows modular apps and libraries to depend on Loader in their module-info files without relying on the file name.
Companion PR to #790 and #793 – being able to use a module-info makes developing for ModLauncher a bit nicer.
=> Add Automatic-Module-Name to jar manifest

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McLibrary.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java
Companion PR to #790. The older one is needed for ModLauncher support, this one is needed for running on ML together with Forge. Forge splits the MC assets into a separate jar on modern versions, so it needs to be recognised as an MC jar as well.
(If it's not recognised, random things like the detected MC version break.)
=> MinecraftGameProvider: Support split assets jar

junit/src/main/java/net/fabricmc/loader/impl/junit/FabricLoaderLauncherSessionListener.java
This allows the EnvType in `FabricLoaderLauncherSessionListener` to be tweaked via the `fabric.side` system property.
With this, server-only mods can also be unit tested.
Closes #804.
Minor detail: It would be better to introduce a utility method somewhere that parses the `fabric.side` property.
I essentially use the same switch block as in `Knot#init`. However, introducing the method to the `fabric-loader` subproject would also require a new version of `fabric-loader` for such a minor feature. Therefore, I've duplicated the parser for now.
One way to tweak the unit-test EnvType, in Gradle buildscripts:
```groovy
tasks {
test {
systemProperty("fabric.side", "server")
}
}
```
I will also open a pull request on loom for automatically adding the property when `loom.serverOnlyMinecraftJar()` …
=> Allow fabric-loader-junit EnvType to be changed

src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassLoader.java
Fix the issue that findResources returns empty due to not overriding findResources.
Added getUrlLoader() to allow developers to access other URLClassLoader methods that are not overridden by KnotClassLoader.
=> Fix call to findResources returns empty.

.gitignore, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/patch/EntrypointPatchFML125.java
The changes in c2a0a0e3491617999cd09d4dcecfff3a2748cd47 broke EntrypointPatchFML125 due to it now only being able to search for ModClassLoader_125_FML in the game jar files, which doesn't work, as ModClassLoader_125_FML is part of Fabric. I've attempted to get around this by just loading ModClassLoader_125_FML from the launcher's class path.
Disclaimer: I'm not very experienced in using ASM, so this might not be the best way of doing this.
=> Unbreak EntrypointPatchFML125, again

src/main/java/net/fabricmc/loader/impl/util/StringUtil.java, src/main/resources/net/fabricmc/loader/Messages_es.properties
This pull request adds a Spanish translation, and adapts `StringUtil.capitalize` slightly to be able to support its leading punctuation (`¡`).
`StringUtil` will now search for the first letter or number instead of choosing always the first character, meaning that strings leaded by punctuation (such as `¡` in my case) will still be capitalized. Number is also checked because I believe `5 mods` is the correct spelling, not `5 Mods`.
I was not able to get JiJ-related strings to trigger.
Also, I think the title "Incompatible mod set!" (and probably the button texts) should be translatable.
=> Add Spanish translation and make `StringUtil` capitalize the first letter, not character

build.gradle, gradle/installer-json.gradle, gradle/launcher.gradle, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
- Generate installer jsons
- Add library hashes + file size
- Shade + repackage tiny-remapper and access-widener these are not part of the public API. (TMP is removed as part of the MIO PR)
- Library hashes are pulled from maven and are commited to the repo.
- Bump installer.json to version 2 for added hashes and `development` library key.
- Add min java version to installer.json
=> Rework external library handling.

src/main/java/net/fabricmc/loader/impl/game/GameProviderHelper.java, src/main/java/net/fabricmc/loader/impl/util/SystemProperties.java
This saves a considerable amount of memory on the first startup. Left a system prob to enable this again if required.
=> Dont debof with classpath by default.

.github/workflows/build.yml, build.gradle, gradle.properties, gradle/installer-json.gradle, minecraft/minecraft-test/build.gradle, minecraft/minecraft-test/src/main/java/net/fabricmc/minecraft/test/mixin/MixinGrassBlock.java, minecraft/minecraft-test/src/test/java/net/fabricmc/minecraft/test/junit/JunitTest.java, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
Supersedes https://github.com/FabricMC/fabric-loader/pull/849
=> Include MixinExtras

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/patch/BrandingPatch.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/patch/EntrypointPatch.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/patch/EntrypointPatchFML125.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/patch/TinyFDPatch.java, src/main/java/net/fabricmc/loader/impl/game/patch/GamePatch.java, src/main/java/net/fabricmc/loader/impl/game/patch/GameTransformer.java
This allows multiple GamePatches to patch the same class by reusing the emitted ClassNode from previous patches. Previously in all but one place the ClassNode was used, so this change should have minimal overhead.
Fixes #819 Blocks #861
=> Fix crash when starting 1.2.5 server

build.gradle, src/main/java/net/fabricmc/loader/impl/discovery/RuntimeModRemapper.java
Tested with a mix of mods using both old and new.
=> Use TR's MixinExtension to remap jars built without refmaps in dev.

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McVersionLookup.java
This fixes version lookup of 1.20.5 breaking with latest snapshot (24w03a)
=> Added support for 1.20.5 in 2024 in McVersionLookup

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McVersionLookup.java
Between 1.2 and the mid-1.7s, Mojang had a weird versioning system where pre-releases would 'reserve' a version number, and if additional pre-releases were required, the version number would be bumped. This led to some minor versions being 'skipped', which was not previously accounted for in Loader's version detection for snapshots.
The snapshot 12w42b, for example, was followed by 1.4 pre-release, and 1.4.1 pre-release, before 1.4.2 became the first stable 1.4.x version. Previously, 12w42b would have been detected by Loader as a 1.4.2 snapshot - technically correct, but would have made its semver place it *after* 1.4 and 1.4.1, which is incorrect.
This PR fixes all such cases.
=> Fix edge case with early snapshot version detection

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/patch/EntrypointPatch.java, src/main/java/net/fabricmc/loader/impl/discovery/ModDiscoverer.java, src/main/java/net/fabricmc/loader/impl/metadata/BuiltinModMetadata.java
This should allow running Loader for weird MC releases, with limited mod -> game version range comparison support of course.
It logs a warning in production, but throws an error in-dev since devs are more able to use the system property and we don't want to miss the limited normalization support.
=> Support non-semver game versions

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McVersionLookup.java
This fixes version lookup of 1.21 breaking with latest snapshot (24w18a)
=> Added support for 1.21 (for snapshots >= 24w18a) in McVersionLookup

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/launchwrapper/FabricTweaker.java, src/main/java/net/fabricmc/loader/impl/discovery/RuntimeModRemapper.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassDelegate.java, src/main/java/net/fabricmc/loader/impl/util/ManifestUtil.java
This bypasses the URL connection for cases where the jar file may not be used after startup.
Needs testing
(hopefully) fixes https://github.com/FabricMC/fabric-loader/issues/920
=> Avoid jar cache when reading Manifest, reserve URL based method for special cases only

src/main/java/net/fabricmc/loader/impl/launch/MappingConfiguration.java, src/main/java/net/fabricmc/loader/impl/transformer/FabricTransformer.java, src/main/java/net/fabricmc/loader/impl/util/SystemProperties.java
- independent of game provider
- the launch arg is parsed after the game provider is initialized (so that the mapping configuration is loaded)
=> add a system property to enable fixing package access regardless of target namespace

src/main/java/net/fabricmc/loader/api/entrypoint/EntrypointContainer.java, src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/entrypoint/EntrypointContainerImpl.java, src/main/java/net/fabricmc/loader/impl/entrypoint/EntrypointStorage.java
Due to the way I use entrypoints in my projects I tend to encounter entrypoint crashes often while developing.
The current logging makes it hard to distinguish which entrypoint is being problematic at a glance.
This small change in fabric loader specifies in the log the exact entrypoint that caused the game to crash.
Essentially changes:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'minecraft-test'!
at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[main/:?]
```
into:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'minecraft-test->(0.3.x)net.fabricmc.minecraft.test.TestEntrypoint::makeCrashPlz'!
at …
```
=> Specify full entrypoint name on crash

src/main/java/net/fabricmc/loader/impl/discovery/ClasspathModCandidateFinder.java, src/main/java/net/fabricmc/loader/impl/discovery/DirectoryModCandidateFinder.java, src/main/java/net/fabricmc/loader/impl/discovery/ModDiscoverer.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassDelegate.java, src/test/java/net/fabricmc/loader/impl/discovery/GetNonFabricModsTest.java
This removes some theoretically redundant path normalization, only doing some extra validation with asserts enabled (`-ea`)
Fixes https://github.com/FabricMC/fabric-loader/issues/970
=> Use less path normalization due to poor performance on Windows

build.gradle, minecraft/minecraft-test/build.gradle, settings.gradle, src/java17/java/net/fabricmc/loader/impl/mrj/AbstractSecureClassLoader.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassLoader.java, src/main/java/net/fabricmc/loader/impl/mrj/AbstractSecureClassLoader.java
Sets the class loader name, this means stacktraces indicate what classloader a given class was loaded from.
Questions:
- What name should the classloader have? I chose `fabric` over `knot` as this will be seen by anyone looking at log files, knot is very much an internal name to loader, with little meaning.
- Should it target java 9? I went with java 17 + to possibly reduce the number of MRJ versions we may need in the future
=>  Create an MRJ to set the classloader name

src/main/java/net/fabricmc/loader/impl/util/LoaderUtil.java
Also futureproofs the checks just in case the class names are changed.
I was encountering issues with `org.objectweb.asm.Type` being loaded by both the knot classloader, and the app class loader. I removed ASM entirely and was thoroughly confused that the error message stated that were duplicate ASM classes.
Related to #965 
```
Exception in thread "main" java.lang.ExceptionInInitializerError
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: duplicate ASM classes found on classpath: 
at net.fabricmc.loader.impl.util.LoaderUtil.verifyClasspath(LoaderUtil.java:71)
at net.fabricmc.loader.impl.launch.knot.Knot.<clinit>(Knot.java:345)
... 1 more
```
```
Exception in thread "main" java.lang.ExceptionInInitializerError
at …
```
=> Fix LoaderUtil saying there are duplicate classpath entries if there are in fact none.

.github/workflows/build.yml
As discussed on the Fabric Discord server (`#toolchain-other`).
Bumping `actions/upload-artifact` to `v4` to prepare for the [deprecation of v3](https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/).
=> Update build.yml to actions/upload-artifact@v4

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/patch/EntrypointPatch.java
Extra synthetic methods were introduced in `net/minecraft/server/Main` and the restrictions to get `serverStartMethod` became a bit too loose so I added a special case.
=> Add support for 25w14craftmine dedicated servers
