src/main/java/chorusmc/base/launch/ChorusClientTweaker.java, src/main/java/chorusmc/base/mixin/client/MixinClientBrandRetriever.java, src/main/java/chorusmc/base/mixin/client/gui/impl/MixinGuiMain.java, src/main/java/chorusmc/base/mixin/common/server/MixinMinecraftServer.java, src/main/resources/chorusmc.mixins.common.json
The only common mixin I have added is MixinMinecraftServer
=> Add common mixins

src/main/java/net/fabricmc/base/launch/FabricClientTweaker.java, src/main/java/net/fabricmc/base/mixin/client/MixinMinecraft.java
This builds a foundation for the loading screen later, and improves perceived responsiveness.
=> Create the Display extremely early in the tweaker

src/main/java/net/fabricmc/base/mixin/client/MixinMinecraftGame.java
This fixes the initial crash of the minecraft launcher,
http://pastebin.com/99p9K8Jn
=> Fixed initial minecraft launcher crash

src/main/java/net/fabricmc/loader/launch/FabricClientTweaker.java
This is a simple cross platform way of being able to see at a glace if fabric is installed.
=> Set the version type to Fabric

src/main/java/net/fabricmc/loader/language/JavaLanguageAdapter.java
It is currently testing the wrong string. Also cleaned up a bit.
=> Fix bug causing ClientModInitializer/DedicatedServerModInitializers being loaded when they should not be

src/main/java/net/fabricmc/loader/launch/server/FabricServerLauncher.java
=> store server .JAR path in properties file

src/main/java/net/fabricmc/loader/entrypoint/hooks/EntrypointBranding.java
Migration/adaption of https://github.com/FabricMC/fabric-loader/pull/74
I would implement environment context but it increases the complexity of the injection, which is not ideal.
=> Improve branding hook

src/main/java/net/fabricmc/loader/discovery/ModResolver.java
As previously any exceptions just *hung around* and were ignored forever.
This should fix #89.
=> Add exception handling to ModResolver.resolve()

src/main/java/net/fabricmc/loader/discovery/ModResolver.java
https://gist.github.com/UnRealDinnerbone/9ead1c81477e13e3dd1985c65b94a8d2
Seems minecraft maven is down, so I could not run and test. Should have no compile errors.
Signed-off-by: liach <liach@users.noreply.github.com>
=> Use concurrent hash map for something in fork join pool

gradle.properties, src/main/java/net/fabricmc/loader/entrypoint/EntrypointPatch.java, src/main/java/net/fabricmc/loader/entrypoint/minecraft/EntrypointPatchHook.java
I hope this is correct, I had to use vscode to debug this as the new idea update wasnt having any of it.
It seems to work on 1.14.4 and 1.15, bit ugly but works.
=> Quick and dirty fix to #156

src/main/java/net/fabricmc/loader/gui/FabricGuiEntry.java
Instead of sending it to syserr, this will send it to sysout. Is that ok (or even important compared to *not logging it at all*)
=> Fix the error gui not logging the actual error.

build.gradle, gradle.properties, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
Update mixin to the release build, done a small amount of testing, it should be fine due to the small number of mixin changes.
=> Update mixin to 0.8 release

gradle.properties, src/main/java/net/fabricmc/loader/minecraft/McVersionLookup.java
=> Fix ability to load alpha versions

gradle.properties, src/main/java/net/fabricmc/loader/entrypoint/minecraft/EntrypointPatchHook.java
=> Fix Dedicated server entrypoint hook

gradle.properties, src/main/java/net/fabricmc/loader/transformer/accesswidener/AccessWidener.java, src/main/java/net/fabricmc/loader/transformer/accesswidener/AccessWidenerVisitor.java
Also skips over making static methods final
=> Fix making constructors final

src/main/java/net/fabricmc/loader/entrypoint/EntrypointPatch.java, src/main/java/net/fabricmc/loader/entrypoint/EntrypointTransformer.java, src/main/java/net/fabricmc/loader/entrypoint/minecraft/EntrypointPatchHook.java, src/main/java/net/fabricmc/loader/launch/FabricTweaker.java, src/main/java/net/fabricmc/loader/launch/common/FabricLauncher.java, src/main/java/net/fabricmc/loader/launch/knot/Knot.java, src/main/java/net/fabricmc/loader/launch/knot/KnotClassDelegate.java, src/main/java/net/fabricmc/loader/launch/knot/KnotClassLoader.java, src/main/java/net/fabricmc/loader/launch/knot/KnotCompatibilityClassLoader.java, src/main/java/net/fabricmc/loader/launch/knot/MixinServiceKnot.java
=> Fix access wideners not being applied according to mixin

src/main/java/net/fabricmc/loader/entrypoint/minecraft/EntrypointPatchHook.java
Since 20w22a, net.minecraft.server.Main executes a datapack reload before the dedicated server object is constructed. This breaks any mod that adds functionality using datapacks, and crashes Minecraft on the dedicated server when using such mods.
This pull request modifies EntrypointPatchHook to detect 20w22a+ and patch Main rather than MinecraftDedicatedServer. Patching is based on the location of the --safeMode logging message, which is somewhat hacky, but is likely to work as long as that message remains in the codebase.
=> Add 20w22a dedicated server support

build.gradle, src/main/java/net/fabricmc/api/ClientModInitializer.java, src/main/java/net/fabricmc/api/DedicatedServerModInitializer.java, src/main/java/net/fabricmc/api/EnvType.java, src/main/java/net/fabricmc/api/Environment.java, src/main/java/net/fabricmc/api/EnvironmentInterface.java, src/main/java/net/fabricmc/api/EnvironmentInterfaces.java, src/main/java/net/fabricmc/api/ModInitializer.java, src/main/java/net/fabricmc/loader/api/EntrypointException.java, src/main/java/net/fabricmc/loader/api/FabricLoader.java, src/main/java/net/fabricmc/loader/api/LanguageAdapter.java, src/main/java/net/fabricmc/loader/api/LanguageAdapterException.java, src/main/java/net/fabricmc/loader/api/MappingResolver.java, src/main/java/net/fabricmc/loader/api/ModContainer.java, src/main/java/net/fabricmc/loader/api/SemanticVersion.java, src/main/java/net/fabricmc/loader/api/Version.java, src/main/java/net/fabricmc/loader/api/entrypoint/EntrypointContainer.java, src/main/java/net/fabricmc/loader/api/entrypoint/PreLaunchEntrypoint.java, src/main/java/net/fabricmc/loader/api/metadata/ContactInformation.java, src/main/java/net/fabricmc/loader/api/metadata/CustomValue.java, src/main/java/net/fabricmc/loader/api/metadata/ModDependency.java, src/main/java/net/fabricmc/loader/api/metadata/ModMetadata.java, src/main/java/net/fabricmc/loader/api/metadata/Person.java
Associated with FabricMC/yarn#1268 and FabricMC/fabric#550. This allows us to have javadoc for all three most important user-facing components of Fabric.
=> Generate javadocs for loader

src/main/java/net/fabricmc/loader/FabricLoader.java, src/main/java/net/fabricmc/loader/entrypoint/minecraft/EntrypointPatchHook.java
Tested this in dev on 1.16.1. (maven local'd it)
This is my first time touching this code so feel free to question parts of it. My explanation on how I found the dedicated server constructor is listed in the comments
thanks to @ramidzkh for helping me figure out a bit of the bytecode.
=> Inject game instance on 20w22a+ dedicated servers. This fixes #257.

src/main/java/net/fabricmc/loader/api/metadata/ModEnvironment.java, src/main/java/net/fabricmc/loader/api/metadata/ModMetadata.java, src/main/java/net/fabricmc/loader/discovery/BuiltinMetadataWrapper.java, src/main/java/net/fabricmc/loader/metadata/BuiltinModMetadata.java, src/main/java/net/fabricmc/loader/metadata/ModMetadataParser.java, src/main/java/net/fabricmc/loader/metadata/ModMetadataV0.java, src/main/java/net/fabricmc/loader/metadata/ModMetadataV1.java
Useful so I don't need the `modmenu:clientsideOnly` custom element anymore.
=> Expose environment in ModMetadata

build.gradle, src/main/java/net/fabricmc/loader/discovery/ModResolver.java, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
A JIMFS update may help as well as we dont have https://github.com/google/jimfs/commit/989957df7e7fce1f025818e4ccd5a416636dcd51 However there hasnt been an offical release for a number of years.
Basically the same issue as https://github.com/FabricMC/fabric-loader/commit/69d7456f65826f2969c7177732c4a592eacae945
=> Update JIMFS. Should fix #210

src/main/java/net/fabricmc/loader/entrypoint/minecraft/EntrypointPatchHook.java
This is to solve two issues with the current entrypoint:
`server.properties` is loaded before all mods
Mods cannot register their own `GeneratorType` on the dedicated server before the generator type is selected. Late init is possible for this but it increases the late-init hack count to 2 for a future generator type api.
Also there is an issue with biomes api where the nether's generator type is ALWAYS forced to be vanilla nether generator due to late init hack always using the default nether generator.
However this solution comes at the cost of mod init being done before the eula is checked, so the game may be terminated before the server is started. Moving the eula logic ahead of mod init is out of scope for this PR. Regarding vanilla, registries are all boostraped before …
=> Move server entrypoint in 20w22a+ before `server.properties` is loaded.

src/main/java/net/fabricmc/loader/launch/knot/KnotClassLoader.java
This fixes https://github.com/FabricMC/fabric-language-kotlin/issues/25
Tested with AOF
=> Implement findResource in KnotClassLoader

src/main/java/net/fabricmc/loader/entrypoint/minecraft/EntrypointPatchFML125.java
ramidzkh forgot to change one word. Here's this in action: https://discordapp.com/channels/507304429255393322/523251999899385875/752418129417732146.
=> Unbreak EntrypointPatchFML125

src/main/java/net/fabricmc/loader/discovery/ModResolver.java
Currently, there are more than a few cryptic error messages in Loader which make it hard for end users to understand what's wrong. There are three main categories:
- Zip END header not found
- This is caused, to my knowledge, when a mod jar has an issue while downloading and is corrupted. The `zipfs` methods for loading zip file systems don't have signatures that note they can throw a `ZipError`, even though they do throw a `ZipError` if the jar is corrupt. I've added a catch for this and instead throw a `RuntimeException` which notes which jar is corrupt. This will fix #185
- Call the solve method first!!!
- Loader uses `sat4j` for solving mod resolution problems, and makes assumptions about solvedness when it shouldn't. This leads to issues like #201 when a JiJ'd mod has unmet …
=> Clean up mod resolution error messages

src/main/java/net/fabricmc/loader/discovery/ModResolver.java
=> Add the current Java version as a built-in dependency

src/main/java/net/fabricmc/loader/launch/knot/Knot.java, src/main/java/net/fabricmc/loader/launch/knot/KnotClient.java, src/main/java/net/fabricmc/loader/launch/knot/KnotServer.java
I made this so I can have mixins applied in my unit tests, I didn't include the JUnit runner in here because I'm not sure if you'd want me to.
=> Separate Launch

src/main/java/net/fabricmc/loader/entrypoint/minecraft/EntrypointPatchHook.java
=> Fix a warning caused by making InsnList iterable

src/main/java/net/fabricmc/loader/game/MinecraftGameProvider.java, src/main/java/net/fabricmc/loader/metadata/BuiltinModMetadata.java, src/main/java/net/fabricmc/loader/minecraft/McVersion.java, src/main/java/net/fabricmc/loader/minecraft/McVersionLookup.java, src/test/java/net/fabricmc/test/McVersionLookupTest.java
=> Add a Java dependency to the built-in Minecraft mod

src/main/java/net/fabricmc/loader/transformer/FabricTransformer.java
=> Access wideners can now target classes in 'com.mojang.blaze3d' package

src/main/java/net/fabricmc/loader/api/metadata/ModMetadata.java, src/main/java/net/fabricmc/loader/impl/metadata/AbstractModMetadata.java
Deprecated for ~2 years, very few uses, allows removing GSON from loader
=> Remove deprecated ModMetadata.getCustomElement

src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/discovery/ModCandidateSet.java, src/main/java/net/fabricmc/loader/impl/discovery/ModDiscoverer.java, src/main/java/net/fabricmc/loader/impl/discovery/ModResolutionException.java, src/main/java/net/fabricmc/loader/impl/discovery/ModResolver.java, src/main/java/net/fabricmc/loader/impl/metadata/ModDependencyImpl.java
This splits discovery and resolving, changes error message assembly to String.format and does one minor functional change in ModDependencyImpl (log instead of print). Actual code changes will follow in further PRs.
=> Refactor ModResolver

src/main/java/net/fabricmc/loader/impl/metadata/ModMetadataParser.java, src/main/java/net/fabricmc/loader/impl/metadata/V0ModMetadataParser.java, src/main/java/net/fabricmc/loader/impl/metadata/V1ModMetadataParser.java
Closes #392
Signed-off-by: liach <liach@users.noreply.github.com>
=> Port of #392 with player's desired changes

src/main/java/net/fabricmc/loader/impl/util/log/log4j/Level.java, src/main/java/net/fabricmc/loader/impl/util/log/log4j/LogManager.java, src/main/java/net/fabricmc/loader/impl/util/log/log4j/Logger.java, src/main/java/net/fabricmc/loader/impl/util/log/log4j/LoggerImpl.java
This emulates Log4J enough for Mixin to be happy after some remapping.
=> Add Log4J bridge/emulation

src/main/java/net/fabricmc/api/Environment.java
package-info.java gives error as they try to use environment decorator on their package
=> Add package to Environment

src/main/java/net/fabricmc/loader/impl/discovery/ModDiscoverer.java, src/main/java/net/fabricmc/loader/impl/discovery/ModSolver.java, src/main/java/net/fabricmc/loader/impl/util/SystemProperties.java
Also bumps default discovery timeout to 60s, just in case
=> Add debug system properties for the mod discovery and resolution timeouts

src/main/java/net/fabricmc/loader/api/FabricLoader.java, src/main/java/net/fabricmc/loader/api/ObjectShare.java, src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/ObjectShareImpl.java
A simple map-like container for inter-mod communication See the linked issue for why there is no sufficient benefit to make it appear more type safe.
resolves https://github.com/FabricMC/fabric-loader/issues/463
=> Add object share

src/main/java/net/fabricmc/loader/impl/discovery/ModCandidate.java, src/main/java/net/fabricmc/loader/impl/discovery/ModResolver.java, src/main/java/net/fabricmc/loader/impl/discovery/ResultAnalyzer.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassDelegate.java, src/main/java/net/fabricmc/loader/impl/metadata/AbstractModMetadata.java, src/main/java/net/fabricmc/loader/impl/metadata/BuiltinModMetadata.java, src/main/java/net/fabricmc/loader/impl/metadata/ModDependencyImpl.java, src/main/java/net/fabricmc/loader/impl/metadata/V0ModMetadata.java, src/main/java/net/fabricmc/loader/impl/metadata/V1ModMetadata.java, src/main/java/net/fabricmc/loader/impl/util/Localization.java, src/main/java/net/fabricmc/loader/impl/util/StringUtil.java, src/main/resources/net/fabricmc/loader/Messages.properties
Better errors/messages for mod resolution issues and warnings.
Fixes #380
Fixes #456
Fixes #476
=> Improve mod resolution errors

src/main/java/net/fabricmc/loader/impl/util/version/SemanticVersionImpl.java, src/main/java/net/fabricmc/loader/impl/util/version/VersionPredicateParser.java, src/main/legacyJava/net/fabricmc/loader/DependencyException.java, src/main/legacyJava/net/fabricmc/loader/util/version/SemanticVersionImpl.java, src/main/legacyJava/net/fabricmc/loader/util/version/SemanticVersionPredicateParser.java
=> Add more legacy API for compatibility with mods that access Loader core

build.gradle, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
Pending testing (espcially on older versions)
=> Update tiny remapper to support 21w37a

src/main/java/net/fabricmc/loader/metadata/BuiltinModMetadata.java
A niche use case, but my example is [Not So New](https://github.com/Chocohead/Not-So-New) which effectively lowers the Minecraft `java` dependency down from 16 to 8.
=> Allow overriding built in dependencies

build.gradle, src/main/java/net/fabricmc/loader/impl/discovery/RuntimeModRemapper.java, src/main/java/net/fabricmc/loader/impl/transformer/FabricTransformer.java, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
via the V2 version of the library ~~(not yet released, but merged into master)~~
=> Added support for global access wideners

.github/workflows/build.yml, .github/workflows/release.yml, build.gradle
=> Fix build on JDK 17

src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/launch/FabricMixinBootstrap.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassDelegate.java, src/main/java/net/fabricmc/loader/impl/util/SystemProperties.java
Just a few QOL improvements for debugging issues.
=> Better Mixin config creation failure, and -Dfabric.debug.logTransformErrors and add parent mod to mod list

src/main/java/net/fabricmc/loader/api/ModContainer.java, src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/ModContainerImpl.java
For use cases such as https://github.com/FabricMC/fabric/pull/1462
=> Expose containing and contained mods in ModContainer

src/main/java/net/fabricmc/loader/impl/discovery/ModSolver.java
=> Fix breaks clause against pre-selected mods (like the game).

src/main/java/net/fabricmc/loader/impl/FabricLoaderImpl.java, src/main/java/net/fabricmc/loader/impl/FormattedException.java, src/main/java/net/fabricmc/loader/impl/discovery/ModDiscoverer.java, src/main/java/net/fabricmc/loader/impl/discovery/ModResolutionException.java, src/main/java/net/fabricmc/loader/impl/discovery/ResultAnalyzer.java, src/main/java/net/fabricmc/loader/impl/gui/FabricGuiEntry.java, src/main/java/net/fabricmc/loader/impl/gui/FabricMainWindow.java, src/main/java/net/fabricmc/loader/impl/gui/FabricStatusTree.java, src/main/java/net/fabricmc/loader/impl/util/StringUtil.java
This adds line wrapping and removes info with a bad clutter/benefit ratio.
=> Tweak error display

src/main/java/net/fabricmc/loader/impl/discovery/ModResolver.java
Avoids some pointless unfixable recommendations / warnings on server startup
=> Suppress recommends warnings if the dependency is present but disabled for the env

.github/workflows/release.yml, build.gradle
~~Testing should be done to ensure this doesnt cause any weird runtime issues?~~ Seems to work fine.
=> Jar and PGP sign maven artifacts.

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/Log4jLogHandler.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/Slf4jLogHandler.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/launchwrapper/FabricTweaker.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/patch/ModClassLoader_125_FML.java, src/main/java/net/fabricmc/loader/impl/discovery/ArgumentModCandidateFinder.java, src/main/java/net/fabricmc/loader/impl/discovery/ClasspathModCandidateFinder.java, src/main/java/net/fabricmc/loader/impl/discovery/ModDiscoverer.java, src/main/java/net/fabricmc/loader/impl/game/GameProviderHelper.java, src/main/java/net/fabricmc/loader/impl/game/LibClassifier.java, src/main/java/net/fabricmc/loader/impl/game/LoaderLibrary.java, src/main/java/net/fabricmc/loader/impl/game/patch/GameTransformer.java, src/main/java/net/fabricmc/loader/impl/gui/FabricGuiEntry.java, src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassDelegate.java, src/main/java/net/fabricmc/loader/impl/launch/knot/MixinLogger.java, src/main/java/net/fabricmc/loader/impl/launch/server/FabricServerLauncher.java, src/main/java/net/fabricmc/loader/impl/metadata/DependencyOverrides.java, src/main/java/net/fabricmc/loader/impl/util/LoaderUtil.java, src/main/java/net/fabricmc/loader/impl/util/ManifestUtil.java, src/main/java/net/fabricmc/loader/impl/util/SimpleClassPath.java, src/main/java/net/fabricmc/loader/impl/util/UrlUtil.java, src/main/java/net/fabricmc/loader/impl/util/log/BuiltinLogHandler.java, src/main/java/net/fabricmc/loader/impl/util/log/ConsoleLogHandler.java, src/main/java/net/fabricmc/loader/impl/util/log/LogCategory.java, src/main/legacyJava/net/fabricmc/loader/launch/common/FabricLauncherBase.java, src/main/legacyJava/net/fabricmc/loader/util/UrlUtil.java
The class loader appears to normalize them as well, causing its paths to not match those inferred by Loader previously
=> Normalize symlinks

src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassDelegate.java
Should fix issues like https://mclo.gs/Qg6aGb7
=> Skip code source operations for URLs with unknown protocols (injected by hacky mods)

src/main/java/net/fabricmc/loader/impl/discovery/ModDiscoverer.java
For use with https://github.com/FabricMC/fabric-loom/pull/695
Just a minimal change PR, could possibly check to ensure only one path is a mod?
=> Support mods from multiple jars and directories.

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McVersionLookup.java
1.19.3+ needs this again, better solution wip
=> Extend hardcoded snapshot version to release mapping

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/MinecraftGameProvider.java, minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/patch/EntrypointPatch.java
Fixes https://github.com/FabricMC/fabric/issues/2879
Will need testing on most major MC versions.
=> Improve the entrypoint patch reliability.

gradle.properties, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
=> Update to ASM 9.5

gradle.properties, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
=> Update to ASM 9.6

src/main/java/net/fabricmc/loader/impl/launch/knot/Knot.java, src/main/java/net/fabricmc/loader/impl/util/LoaderUtil.java
Fail early and nicely instead of weirdly and wonderfully.
=> Check for duplicate copies of loader on the classpath.

build.gradle, gradle.properties, src/main/resources/fabric-installer.json, src/main/resources/fabric-installer.launchwrapper.json
No code changes, just some new javadocs.
=> Update to Mixin Extras 0.3.1

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McVersionLookup.java
The usual PR for McVersionLookup. This fixes version detection for the latest snapshot.
=> Added support for 1.21.2 in McVersionLookup

src/main/java/net/fabricmc/loader/impl/launch/knot/Knot.java, src/main/java/net/fabricmc/loader/impl/util/LoaderUtil.java
Maybe we should also verify that the version is correct, but this is a good start.
=> Verify that ASM is only on the classpath once.

minecraft/src/main/java/net/fabricmc/loader/impl/game/minecraft/McVersionLookup.java
The usual PR for McVersionLookup
=> Added support for 1.21.4 in McVersionLookup

build.gradle, src/main/java/net/fabricmc/loader/impl/discovery/RuntimeModRemapper.java, src/main/java/net/fabricmc/loader/impl/game/GameProviderHelper.java, src/main/java/net/fabricmc/loader/impl/util/log/TinyRemapperLoggerAdapter.java
Now with a proper logging setup :)
=> Update Tiny Remapper

.github/workflows/build.yml, .github/workflows/manage_issues.yml, .github/workflows/release.yml, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, junit/build.gradle, minecraft/minecraft-test/build.gradle, settings.gradle
- Gradle 9
- Loom 1.11 (requires Java 21)
- Use loom's own ClientProductionRunTask
=> Update build dependencies
